# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fd2a9bc2aa647cb9382b442070e6ddef752782003554e2786ef87ce3d5c6b5cdeb82a8fa81ebd6bdb9379c5ebe508f6d349420061eb5958f803e1eaee97c19

test:
  secret_key_base: b56a8922cec4eadd48174d5beee43e3fc1bed79169a5f4d65589cf9c8d85c9f9c6397accbd98655c0f3eadce09841cf1369b2a0826cf89ded352ee320d611951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
